### ISSUE TITLE
RuntimeException crash in intercom.

### ISSUE THREAD

**Issue by manishkungwani** [intercom/intercom-android#85]
Hi,
Please have a look at this Exception I got in my app:

java.lang.RuntimeException: Could not dispatch event: class io.intercom.android.sdk.models.Events.ConversationEvent to handler [EventHandler public void io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(io.intercom.android.sdk.models.Events.ConversationEvent)]: setSpan (0 ... 144) ends beyond length 138
       at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
       at com.squareup.otto.Bus.dispatch(Bus.java:387)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at com.squareup.otto.Bus.post(Bus.java:337)
       at io.intercom.android.sdk.api.MainThreadBus.post(MainThreadBus.java:22)
       at io.intercom.android.sdk.api.CallbackHolder$5.success(CallbackHolder.java:83)
       at io.intercom.android.sdk.api.CallbackHolder$5.success(CallbackHolder.java:81)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: java.lang.IndexOutOfBoundsException: setSpan (0 ... 144) ends beyond length 138
       at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:351)
       at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
       at android.text.SpannableString.setSpan(SpannableString.java:46)
       at io.intercom.android.sdk.blocks.UnorderedList.addUnorderedList(UnorderedList.java:61)
       at io.intercom.android.blocks.BlockType$4.generateView(BlockType.java:25)
       at io.intercom.android.blocks.Blocks.createBlocks(Blocks.java:32)
       at io.intercom.android.sdk.conversation.BaseConversationFragment.createMessageUI(BaseConversationFragment.java:125)
       at io.intercom.android.sdk.conversation.ConversationFragment.createConversationUI(ConversationFragment.java:572)
       at io.intercom.android.sdk.conversation.ConversationFragment.setupWithConversation(ConversationFragment.java:512)
       at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:362)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
       at com.squareup.otto.Bus.dispatch(Bus.java:385)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at com.squareup.otto.Bus.post(Bus.java:337)
       at io.intercom.android.sdk.api.MainThreadBus.post(MainThreadBus.java:22)
       at io.intercom.android.sdk.api.CallbackHolder$5.success(CallbackHolder.java:83)
       at io.intercom.android.sdk.api.CallbackHolder$5.success(CallbackHolder.java:81)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by Harkin** [comment]
That was an issue with some html content in a list item not being correctly counted towards the length of the string, it's fixed in the latest version

**Comment by danikula** [comment]
@harkin Please explain what kind of html may force this crash? This issue crashed tons of my users yesterday.

**Comment by harkin** [comment]
@danikula I believe it was some markup, like italics, that was causing the issue. We were measuring the length of the string before and after interpreting that markup and using the wrong length for a span

**Comment by lithid** [comment]
We are running on build 1.1.9 and are seeing this crash happen still. I just updated the library to 1.1.12 and have our app ready for beta on Monday, but I see no fixes for this between 1.1.9-1.1.12. I think this issue still exists, or something new was introduced.

[report.txt](https://github.com/intercom/intercom-android/files/92941/report.txt)

**Comment by harkin** [comment]
@lithid that looks like a new issue to me, I'll open an issue for it tomorrow (if you don't beat me to it)
